

source 'https://rubygems.org'

gem 'rails', '~> 4.2.3'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pg', '0.18.4'
#gem 'protected_attributes' #for rails 4.2.6
# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier' , '>= 1.0.3'
  gem 'font-awesome-rails'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'
gem 'bcrypt'
# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'
gem 'pry', '0.10.4', :group => :development
gem "pry-nav" ,:group => :development
# To use debugger
# gem 'debugger'
gem 'addressable'
gem "devise"
gem 'database_cleaner'
gem 'cancan'
gem 'rolify'
gem 'carrierwave'
gem 'mini_magick'
gem "kaminari" 
gem 'google_drive' , '1.0.6'
gem "google_visualr" , ">= 2.1"
gem 'thin'
gem "mail"
gem 'sass'
gem 'execjs'
gem 'therubyracer'
gem 'faraday'
gem 'koala'
gem 'inherited_resources'
#gem "mime-types", '2.6.2'
# the following section is added by Josh
# section for seo
#gem 'seo_helper', '~> 1.0.2'
gem 'meta-tags', '~> 2.0.0'
gem 'open_graph_helper'
# Fetch settings
gem 'rack' 
gem 'settingslogic'
# for bootstrap
gem 'bootstrap_helper'
gem "bootstrap-kaminari-views"
#gem 'activeadmin', '1.0.0.pre4', :git => 'https://github.com/gregbell/active_admin.git' 
gem 'activeadmin'
gem  'googleauth' , '0.5.1'
gem  'oauth'
gem  'oauth2'
gem 'nokogiri'
gem 'geocoder'
gem 'gmaps4rails'
gem 'gon'
#gem "mime-types", '2.6.2'  #for rails 4.2.6
#gem 'signet', '>= 0.5.0'
#gem 'google-api-client'
gem 'public_suffix'
gem 'hashie' 
gem 'omniauth'
gem 'omniauth-oauth2'
gem 'omniauth-facebook'
gem 'omniauth-google-oauth2' , '0.2.8'
gem "rails_autolink"
gem 'google-api-client' ,'0.8.6'
gem 'delayed_job_active_record' 
gem 'rubyzip'
gem 'axlsx'
gem 'axlsx_rails'
gem 'rake'
gem 'ransack'
gem 'rack-cache' 
gem 'protected_attributes'
gem 'responders', '~> 2.0'